import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-10`}
      >
        <nav className="flex gap-2">
          <Link
            href="/signup"
            className="bg-blue-500 text-white p-1 font-semibold rounded-md"
          >
            sign up
          </Link>
          <Link
            href="/signin"
            className="bg-blue-500 text-white p-1 font-semibold rounded-md"
          >
            sign in
          </Link>
        </nav>
        <div className="mt-10">{children}</div>
      </body>
    </html>
  );
}
